
INSERT INTO ELECTRODOMESTICOS (ELECTRO_ID,ELECTRO_TIPO,CUSTOMER_ID,TIEMPO_USO) VALUES (10308,'Lavavajillas',1,10);
INSERT INTO ELECTRODOMESTICOS (ELECTRO_ID,ELECTRO_TIPO,CUSTOMER_ID,TIEMPO_USO) VALUES (10309,'Aspiradora',2,20);
INSERT INTO ELECTRODOMESTICOS (ELECTRO_ID,ELECTRO_TIPO,CUSTOMER_ID,TIEMPO_USO) VALUES (10310,'Lavadora',3,30);

INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CONTRASENA) VALUES (1,'Alfreds Futterkiste','1');
INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CONTRASENA) VALUES (2,'Ana Trujillo','2');
INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CONTRASENA) VALUES (3,'Antonio Moreno','3');

INSERT INTO PRECIOS (ELECTRO_TIPO,CONSUMO_MEDIO_HORA,PRECIO_CONSUMO) VALUES ('Lavavajillas',10,0.2);
INSERT INTO PRECIOS (ELECTRO_TIPO,CONSUMO_MEDIO_HORA,PRECIO_CONSUMO) VALUES ('Aspiradora',20,0.3);
INSERT INTO PRECIOS (ELECTRO_TIPO,CONSUMO_MEDIO_HORA,PRECIO_CONSUMO) VALUES ('Lavadora',3,0.4);
